### ISSUE TITLE
Possible typo

### ISSUE THREAD

**Issue by bpj** [tarleb/ansi-terminal-writer#1]
Is `cancel` a typo for `stop` on [line 66][]? The `cancel` variable isn't used anywhere and I don't know where the `stop` variable would come from.

[line 66]: https://github.com/tarleb/ansi-terminal-writer/blob/338408811b42aa7ad6763019715eb156b92d0465/ansi-terminal-writer.lua#L66

**Comment by tarleb** [comment]
Indeed, that's a typo. Thank you!
